-- Testcontainers schema fixture, captured verbatim via `SHOW CREATE TABLE`
-- against the preview company database (read-only access, no data was touched).
-- Ordered so foreign-key targets (m01Department, m01EvaluationFormType) exist before
-- the staff and task tables that reference them.

CREATE TABLE `m01Department` (
  `UniqId` bigint(20) NOT NULL AUTO_INCREMENT,
  `DepartmentId` varchar(25) DEFAULT NULL,
  `DepartmentName` varchar(50) DEFAULT NULL,
  `EntryStaff` varchar(25) DEFAULT NULL,
  `EntryDate` datetime DEFAULT NULL,
  `LastAddEditStaff` varchar(25) DEFAULT NULL,
  `LastAddEditDate` datetime DEFAULT NULL,
  `Favourite` bit(1) DEFAULT b'0',
  `DashboardPosition` int(11) DEFAULT 0,
  PRIMARY KEY (`UniqId`),
  UNIQUE KEY `DepartmentId` (`DepartmentId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE `m01EvaluationFormType` (
  `UniqId` bigint(15) NOT NULL AUTO_INCREMENT,
  `FormType` varchar(25) DEFAULT NULL,
  `SkillSet` varchar(25) DEFAULT NULL,
  `EntryStaff` varchar(25) DEFAULT NULL,
  `EntryDate` datetime DEFAULT NULL,
  `LastEditStaff` varchar(25) DEFAULT NULL,
  `LastEditDate` datetime DEFAULT NULL,
  `FormGroup` varchar(30) DEFAULT NULL,
  `URL` varchar(100) DEFAULT NULL,
  `MultipleForms` bit(1) DEFAULT b'0',
  `NonProject` bit(1) DEFAULT b'0',
  PRIMARY KEY (`UniqId`),
  UNIQUE KEY `uq_formtype_skillset` (`FormType`,`SkillSet`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE `m03Staff` (
  `Code` bigint(20) NOT NULL AUTO_INCREMENT,
  `StaffId` varchar(25) NOT NULL,
  `Salute` varchar(20) DEFAULT NULL,
  `Name` varchar(255) NOT NULL,
  `Nric` varchar(20) DEFAULT NULL,
  `CountryOfBirth` varchar(50) DEFAULT NULL,
  `DateOfBirth` datetime DEFAULT NULL,
  `Citizenship` varchar(100) DEFAULT NULL,
  `Race` varchar(50) DEFAULT NULL,
  `Sex` varchar(10) DEFAULT NULL,
  `MartialStatus` varchar(20) DEFAULT NULL,
  `AddBlock` varchar(10) DEFAULT NULL,
  `AddNos` varchar(10) DEFAULT NULL,
  `AddFloor` varchar(10) DEFAULT NULL,
  `AddUnit` varchar(10) DEFAULT NULL,
  `AddBuilding` varchar(100) DEFAULT NULL,
  `AddStreet` varchar(100) DEFAULT NULL,
  `AddPostal` varchar(20) DEFAULT NULL,
  `AddCity` varchar(50) DEFAULT NULL,
  `AddState` varchar(50) DEFAULT NULL,
  `AddCountry` varchar(50) DEFAULT NULL,
  `TelHome` varchar(50) DEFAULT NULL,
  `TelMobile` varchar(255) DEFAULT NULL,
  `TelPager` varchar(50) DEFAULT NULL,
  `Location` varchar(100) DEFAULT NULL,
  `Department` varchar(25) DEFAULT NULL,
  `Profession` varchar(100) DEFAULT NULL,
  `Appointment` varchar(100) DEFAULT NULL,
  `DirectLine` varchar(50) DEFAULT NULL,
  `Extension` varchar(50) DEFAULT NULL,
  `EmailPerson` varchar(50) DEFAULT NULL,
  `EmailCompany` varchar(255) DEFAULT NULL,
  `DateJoin` datetime DEFAULT NULL,
  `DateLeft` datetime DEFAULT NULL,
  `Comments` varchar(500) DEFAULT NULL,
  `SecGroupAuthority` varchar(50) DEFAULT NULL,
  `SecLevel` decimal(18,0) DEFAULT NULL,
  `SecLoginId` varchar(25) DEFAULT NULL,
  `SecPassword` varchar(100) DEFAULT NULL,
  `SecExpiryDate` datetime DEFAULT NULL,
  `Address1` varchar(100) DEFAULT NULL,
  `SecChangePassword` bit(1) DEFAULT NULL,
  `SecDisablePassword` bit(1) DEFAULT NULL,
  `Payroll_Coy` varchar(25) DEFAULT NULL,
  `EmpGroup` varchar(10) DEFAULT NULL,
  `Trade` varchar(25) DEFAULT NULL,
  `Nationality` varchar(50) DEFAULT NULL,
  `SystemUser` varchar(1) DEFAULT NULL,
  `HLEVEL` varchar(200) DEFAULT NULL,
  `HDEPT` varchar(10) DEFAULT NULL,
  `PassPort_Expiry` datetime DEFAULT NULL,
  `Sec_Bond_No` varchar(25) DEFAULT NULL,
  `Sec_Bond_Expiry` datetime DEFAULT NULL,
  `Soc_Cert_No` varchar(25) DEFAULT NULL,
  `Soc_Cert_Expiry` datetime DEFAULT NULL,
  `InterfaceLanguage` varchar(20) DEFAULT NULL,
  `WebPassword` varchar(10) DEFAULT NULL,
  `EntryDate` datetime DEFAULT NULL,
  `HomeBlock` varchar(10) DEFAULT NULL,
  `HomeNos` varchar(10) DEFAULT NULL,
  `HomeFloor` varchar(10) DEFAULT NULL,
  `HomeUnit` varchar(10) DEFAULT NULL,
  `HomeBuilding` varchar(100) DEFAULT NULL,
  `HomeStreet` varchar(100) DEFAULT NULL,
  `HomePostal` varchar(20) DEFAULT NULL,
  `HomeCity` varchar(50) DEFAULT NULL,
  `HomeState` varchar(50) DEFAULT NULL,
  `HomeCountry` varchar(50) DEFAULT NULL,
  `HomeAddress1` varchar(100) DEFAULT NULL,
  `HomeTel` varchar(50) DEFAULT NULL,
  `HomeMobile` varchar(50) DEFAULT NULL,
  `HomePager` varchar(50) DEFAULT NULL,
  `HomeEmail` varchar(50) DEFAULT NULL,
  `Status` varchar(1) DEFAULT NULL,
  `Meal` decimal(18,2) DEFAULT NULL,
  `Transport` decimal(18,2) DEFAULT NULL,
  `Shift` decimal(18,2) DEFAULT NULL,
  `RoomNo` varchar(25) DEFAULT NULL,
  `ShiftCode` varchar(10) DEFAULT NULL,
  `LocationID` varchar(6) DEFAULT NULL,
  `DeptSubLedger` varchar(6) DEFAULT NULL,
  `IR8SIndicator` bit(1) DEFAULT NULL,
  `POSBranch` varchar(10) DEFAULT NULL,
  `JobType_Auth_Users` varchar(200) DEFAULT NULL,
  `WHLocation` varchar(10) DEFAULT NULL,
  `LastAddEdit` datetime DEFAULT NULL,
  `LastAddEditStaff` varchar(25) DEFAULT NULL,
  `znSecPassword` varchar(255) NOT NULL DEFAULT '',
  `PayCompute` varchar(10) DEFAULT NULL,
  `EffectPeriod` varchar(6) DEFAULT NULL,
  `CPFYN` varchar(1) DEFAULT NULL,
  `WorkEnqScreen` varchar(50) DEFAULT NULL,
  `StaffPic` blob DEFAULT NULL,
  `EntryStaff` varchar(25) DEFAULT NULL,
  `SecMobileLoginID` varchar(25) DEFAULT NULL,
  `SecMobilePassword` varchar(100) DEFAULT NULL,
  `SecTabletMobileNo` varchar(50) DEFAULT NULL,
  `SecWebLoginID` varchar(25) DEFAULT NULL,
  `SecWebPassword` varchar(100) DEFAULT NULL,
  `ProjectCode` varchar(25) DEFAULT NULL,
  `HRSecurityLevel` varchar(10) DEFAULT NULL,
  `SecGoogleEmail` varchar(50) DEFAULT NULL,
  `SecGooglePassword` varchar(100) DEFAULT NULL,
  `SecGoogleTaskEvent` bit(1) DEFAULT NULL,
  `SecGoogleJobReqDate` bit(1) DEFAULT NULL,
  `SecGoogleServDate` bit(1) DEFAULT NULL,
  `SlsmanYN` bit(1) DEFAULT NULL,
  `WebDisableYN` bit(1) DEFAULT NULL,
  `OTPYN` bit(1) DEFAULT NULL,
  `WebID` varchar(50) DEFAULT NULL,
  `Passcode` varchar(50) DEFAULT NULL,
  `LeaveGroup` varchar(50) DEFAULT NULL,
  `AnnualLeaveIncrement` decimal(18,2) DEFAULT NULL,
  `MaxBringForward` decimal(18,2) DEFAULT NULL,
  `MaxLeaveEntitlement` decimal(18,2) DEFAULT NULL,
  `EvenDistribution` bit(1) DEFAULT NULL,
  `CustomizedDistribution` bit(1) DEFAULT NULL,
  `SourceCompany` varchar(4) DEFAULT NULL,
  `Photo` blob DEFAULT NULL,
  `VerifyBySMS` bit(1) DEFAULT NULL,
  `Singature` blob DEFAULT NULL,
  `CalendarColor` varchar(10) DEFAULT NULL,
  `PreferredName` varchar(100) DEFAULT NULL,
  `SalesGroup` varchar(200) DEFAULT NULL,
  `CompanyGroup` varchar(200) DEFAULT NULL,
  `Roles` varchar(200) DEFAULT NULL,
  `SecGroupAuthorityTablet` varchar(50) DEFAULT NULL,
  `SecLoginComments` varchar(200) DEFAULT NULL,
  `WebUploadDate` datetime DEFAULT NULL,
  `PRIssueDate` datetime DEFAULT NULL,
  `UploadDate` datetime DEFAULT NULL,
  `IncentiveRate` decimal(18,4) DEFAULT NULL,
  `RptDepartment` varchar(1000) DEFAULT NULL,
  `EmailPassword` varchar(50) DEFAULT NULL,
  `BloodType` varchar(2) DEFAULT NULL,
  `Religion` varchar(50) DEFAULT NULL,
  `SeafileToken` varchar(200) DEFAULT NULL,
  `InternalBranch` varchar(25) DEFAULT NULL,
  `Role` varchar(50) NOT NULL DEFAULT 'USER',
  `FormTypeId` bigint(20) DEFAULT NULL,
  `FormType` varchar(25) DEFAULT NULL,
  `SkillSet` varchar(25) DEFAULT NULL,
  `LastEditStaff` varchar(25) DEFAULT NULL,
  `LastEditDate` datetime DEFAULT NULL,
  `AvatarColor` varchar(10) DEFAULT NULL,
  `TokenGenerated` varchar(255) DEFAULT NULL,
  `TokenExpiryDate` datetime DEFAULT NULL,
  `TokenActivated` varchar(1) DEFAULT 'N',
  PRIMARY KEY (`Code`) USING BTREE,
  UNIQUE KEY `unique_staffid` (`StaffId`),
  KEY `fk_staff_department` (`Department`),
  KEY `fk_staff_formtype` (`FormTypeId`),
  CONSTRAINT `fk_staff_department` FOREIGN KEY (`Department`) REFERENCES `m01Department` (`DepartmentId`),
  CONSTRAINT `fk_staff_formtype` FOREIGN KEY (`FormTypeId`) REFERENCES `m01EvaluationFormType` (`UniqId`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=239 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
CREATE TABLE `m07SystemParameters` (
  `UniqId` bigint(10) NOT NULL AUTO_INCREMENT,
  `EntryStaff` varchar(25) DEFAULT NULL,
  `EntryDate` datetime DEFAULT NULL,
  `LastEditStaff` varchar(25) DEFAULT NULL,
  `LastEditDate` datetime DEFAULT NULL,
  `Parameter` varchar(255) DEFAULT NULL,
  `ParameterValue` varchar(50) DEFAULT NULL,
  `ParameterDescription` varchar(2000) DEFAULT NULL,
  `ModuleId` varchar(25) DEFAULT NULL,
  `IsPublic` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`UniqId`)
) ENGINE=InnoDB AUTO_INCREMENT=48 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
CREATE TABLE `m07UserActionLog` (
  `UniqId` bigint(20) NOT NULL AUTO_INCREMENT,
  `StaffId` varchar(25) DEFAULT NULL,
  `Module` varchar(25) DEFAULT NULL,
  `ReferenceNo` varchar(45) DEFAULT NULL,
  `Action` varchar(25) DEFAULT NULL,
  `LogDate` datetime DEFAULT NULL,
  `DeviceName` varchar(45) DEFAULT NULL,
  `DeviceIPAddress` varchar(25) DEFAULT NULL,
  `DeviceSerialNo` varchar(50) DEFAULT NULL,
  `Remarks` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`UniqId`)
) ENGINE=InnoDB AUTO_INCREMENT=2345 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
CREATE TABLE `m10Attachments` (
  `UniqId` bigint(20) NOT NULL AUTO_INCREMENT,
  `ModuleType` varchar(50) NOT NULL,
  `ReferenceCode` varchar(50) NOT NULL,
  `FileName` varchar(100) NOT NULL,
  `OriginalName` varchar(255) NOT NULL,
  `FileSize` bigint(20) NOT NULL,
  `StorageType` varchar(20) DEFAULT 'LOCAL',
  `ContentType` varchar(100) DEFAULT NULL,
  `FileExtension` varchar(20) DEFAULT NULL,
  `FileData` longblob DEFAULT NULL,
  `FilePath` varchar(500) DEFAULT NULL,
  `Description` varchar(500) DEFAULT NULL,
  `UploadSource` varchar(20) DEFAULT 'WEB',
  `EntryStaff` varchar(50) DEFAULT NULL,
  `EntryDate` datetime DEFAULT current_timestamp(),
  `LastEditStaff` varchar(50) DEFAULT NULL,
  `LastEditDate` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`UniqId`),
  KEY `idx_module_ref` (`ModuleType`,`ReferenceCode`),
  KEY `idx_entry_date` (`EntryDate`)
) ENGINE=InnoDB AUTO_INCREMENT=201 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `m24JobTasks` (
  `UniqID` bigint(20) NOT NULL AUTO_INCREMENT,
  `EntryStaff` varchar(25) NOT NULL,
  `EntryDate` datetime DEFAULT current_timestamp(),
  `LastEditStaff` varchar(25) DEFAULT NULL,
  `LastEdtiDate` datetime DEFAULT NULL,
  `JobTaskId` varchar(25) NOT NULL,
  `TaskTitle` varchar(200) NOT NULL,
  `TaskType` varchar(50) NOT NULL,
  `TaskDescription` varchar(5000) DEFAULT NULL,
  `AssignorStaffID` varchar(25) NOT NULL,
  `AssigneeStaffID` varchar(25) NOT NULL,
  `Priority` varchar(20) NOT NULL,
  `JobStatus` varchar(20) NOT NULL,
  `DueDate` datetime DEFAULT NULL,
  `StartedDate` datetime DEFAULT NULL,
  `CompletedDate` datetime DEFAULT NULL,
  `EstimatedHours` decimal(6,2) DEFAULT NULL,
  `ActualHours` decimal(6,2) DEFAULT NULL,
  `Remarks` varchar(2000) DEFAULT NULL,
  `AttachmentPath` varchar(500) DEFAULT NULL,
  `ReleaseId` varchar(50) DEFAULT NULL,
  `ProgressRemarks` varchar(2000) DEFAULT NULL,
  PRIMARY KEY (`UniqID`)
) ENGINE=InnoDB AUTO_INCREMENT=169 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
CREATE TABLE `m24TaskRelease` (
  `UniqId` bigint(20) NOT NULL AUTO_INCREMENT,
  `EntryStaff` varchar(25) NOT NULL,
  `EntryDate` datetime DEFAULT current_timestamp(),
  `LastEditStaff` varchar(25) DEFAULT NULL,
  `LastEditDate` datetime DEFAULT NULL,
  `ReleaseId` varchar(50) NOT NULL,
  `ReleaseDate` datetime NOT NULL,
  `ReleaseVersion` varchar(50) NOT NULL,
  `ReleaseRemarks` varchar(2000) DEFAULT NULL,
  `ReleaseType` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`UniqId`),
  UNIQUE KEY `uk_m24TaskRelease_ReleaseId` (`ReleaseId`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
